### ISSUE TITLE
Tests for metalctl

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [metal-stack/metalctl#142]
At the moment `metalctl` completely lacks tests. Which makes testing big PRs([example](https://github.com/metal-stack/metalctl/pull/140)) quite a routine. 

Intergration tests would be a great addition. Another, lighter, solution would be adding unit tests with using [`metal-go` mock client](https://github.com/metal-stack/metal-go/blob/5d8bbfc6ca965d11c72733c0aaa430e2cc0b742a/test/client/mock_client.go).

This issue seems to be quite massive to solve it in one PR. Solving it by parts(smaller PRs adding small test coverage) should be more feasible.

cc @Gerrit91

**Comment by Gerrit91** [comment]
All base commands now have unit test coverage (through #146).
