### ISSUE TITLE
Expose Audit Logs in metalctl audit ls

### ISSUE THREAD

**Issue by vknabel** [metal-stack/metalctl#186]
Meilisearch does only provide a searchable web frontend when running in development mode. We want to avoid this and a little bit more convenience.

The approach is to add a subcommand to metalctl to show audit logs: `metalctl audit ls`.

**Comment by Gerrit91** [comment]
Flags that should be available for the user to filter down search results:

- `--request-id 3c56f318-95aa-49c2-afba-53e0336cbb3a` (string starts-with)
- `--path /v1/image` (free search in path field)
- `--user user@metal-stack.io` (exact match?)
- `--tenant metal-stack.io` (exact match?)
- `--from "2023-02-01 15:23:34" --to "2023-02-01 16:45:57"` (defaults to `time.Now() - 1h`)
- `--body "something"` (free text searches on body and response fields)
- ...?

Changes we have to make for the fields in meilisearch:

- Factor out field names into constants / form a common search query struct for the interface?
  - Maybe consider interface refactoring?
- Add unix timestamp to have time searchable queries
- Disable typo tolerance
- Remove duplicate request body from response entry
