### ISSUE TITLE
feature request: implement metalctl machine power hd

### ISSUE THREAD

**Issue by mwennrich** [metal-stack/metalctl#39]
Currently we have:

```
metalctl machine power 

Available Commands:
  bios        boot a machine into BIOS
  off         power off a machine
  on          power on a machine
  reset       power reset a machine
```

There should be options to boot into pxe or hd, too.

Maybe an new command (outside of "power"), like

`metalctl machine boot <hd|pxe|bios>`

**Comment by majst01** [comment]
We can implement this on the client side only and rely solely on the usage of go-hal, then of course a direct access to the bmc network is required.

Maybe both, als for console:

```metalct machine boot [--ipmi] <hd|pxe|bios>```

without ```--ipmi``` metalctl -> metal-api -> metal-core
