### ISSUE TITLE
Support version compatibility check on the wire

### ISSUE THREAD

**Issue by majst01** [metal-stack/metalctl#5]
In order to be able to check from the metalctl side if it is still compatible with metal-api, the wire protocol should introduce a "X-Metal-Stack-API-Version" header field.

additional:
```
metalctl version
metalctl: v1.2.3
metal-api: v2.3.4
```

**Comment by Gerrit91** [comment]
It would be really great to have something like that!

**Comment by Gerrit91** [comment]
Should not be required anymore since https://github.com/metal-stack/metal-lib/pull/117.
