### ISSUE TITLE
cobra 1.0 allows to write bash_completions in go

### ISSUE THREAD

**Issue by majst01** [metal-stack/metalctl#7]
see: https://github.com/spf13/cobra/pull/1035

**Comment by Gerrit91** [comment]
Auto-completion for context cmd? :heart_eyes_cat:

**Comment by majst01** [comment]
I tried this new feature, but was unable to make it work, give it another try later.

**Comment by marckhouzam** [comment]
> I tried this new feature, but was unable to make it work, give it another try later.

Did you have a chance to look at the documentation?
https://github.com/spf13/cobra/blob/v1.0.0/bash_completions.md#dynamic-completion-of-nouns

If that documentation isn't clear or is insufficient we can try to improve it.

**Comment by majst01** [comment]
Did that, will try again, thanks for the pointer.

**Comment by marckhouzam** [comment]
I would have liked to point you to the helm project as an example, but its use of Cobra 1.0 is still pending.

But I have the code written and working if it can help. You can look here:
https://github.com/VilledeMontreal/helm/blob/c89e87b48c3c75e776268cccc8cb9808cd211810/cmd/helm/status.go#L56

**Comment by majst01** [comment]
Hi @marckhouzam 

thanks for your help, got it working, see #10 
Can we raise a PR for cobra to get on the list of projects using it ?

**Comment by majst01** [comment]
https://github.com/spf13/cobra/pull/1094
