### ISSUE TITLE
Provide metalctl docker image

### ISSUE THREAD

**Issue by suckowbiz** [metal-stack/metalctl#8]
Currently there is no Docker Image for the released version v0.6.0, v0.7.0 in place.

Expected behavior:
Succeeding call of `docker pull registry.fi-ts.io/metal/metalctl:v0.6.0`

Experienced behavior:
```bash
$ docker pull registry.fi-ts.io/metal/metalctl:v0.6.0
Error response from daemon: manifest for registry.fi-ts.io/metal/metalctl:v0.6.0 not found: manifest unknown: manifest unknown
```

As of https://github.com/metal-stack/metalctl/blob/master/.github/workflows/release.yml there is some CI flow in place but release of Docker Image is missing by intention or error.

**Comment by Gerrit91** [comment]
There is a docker image, but metalctl is now hosted on Docker Hub. The image is called `metalstack/metalctl:v0.6.0` 

If you need this in metal-roles for Ansible, you probably need to update your metal-roles version.

Please re-open if necessary and there are still issues.

**Comment by suckowbiz** [comment]
Ah ok, then this was an orphan left after moving this away from fits. I am going to seek for the origin and replace with the correct image. Thanks!
